<?php

define('CONTENT_BY_URL_SESSION_DATA_CONTAINER', 'sl3w_data');

define('CONTENT_BY_URL_DEFAULT_IBLOCK_TYPE', 'sl3w_contentbyurl');
define('CONTENT_BY_URL_DEFAULT_IBLOCK_CODE', 'sl3w_contentbyurl');

define('CONTENT_BY_URL_DEFAULT_CACHE_TIME', 360000);

define('CONTENT_BY_URL_DEFAULT_KEY_FIELD_NAME', 'NAME');
define('CONTENT_BY_URL_DEFAULT_VALUE_FIELD_NAME', 'PREVIEW_TEXT');